### ISSUE TITLE
Strange speed loss for Cfish

### ISSUE THREAD

**Issue by JavaMast** [syzygy1/Cfish#118]
Some time ago i found issue  in some positions (with passed pawns?) - Cfish is a lot slower than Stockfish with same bench.
Cfish 9 has not this issue. 

q7/8/2p5/B2p2pp/5pp1/2N3k1/6P1/7K w - - 0 1

Ryzen 3900X, 12 cores (SMT=off), hash 1024 MB no TB:

![Screenshot_671](https://user-images.githubusercontent.com/42765009/87817882-671cf780-c872-11ea-8889-e2fe5edd634a.png)
![Screenshot_672](https://user-images.githubusercontent.com/42765009/87817903-70a65f80-c872-11ea-9c29-23fd7925c240.png)

no LP:
![Screenshot_674](https://user-images.githubusercontent.com/42765009/87818766-d1826780-c873-11ea-97b9-e91edf9ce677.png)

Also no issue on Intell CPUs.

dual Xeon E5-2687w +64Gb, H-T Enabled.
Run with 8 Gb hash per engine and 5-man Syzygy

![Cfish comparison](https://user-images.githubusercontent.com/42765009/87818080-b9f6af00-c872-11ea-9e72-06296b51d422.jpg)

**Comment by syzygy1** [comment]
Does the same problem occur on Intel with Cfish 11a (if you are able to test this)? Cfish 271219 seems quite a bit older.

Are there positions where the problem does not occur?

On the positions where the problem does occur, does it occur on each run?

My first thought is a bug in the smp patch just before Cfish 11.

**Comment by JavaMast** [comment]
I'll try to do some more tests later. The only thing I'm sure of is that this bug appeared a long time ago, possibly before Cfish 10.

![Screenshot_677](https://user-images.githubusercontent.com/42765009/87845315-dde7de00-c8ce-11ea-94d9-e77f841a4816.png)
![Screenshot_678](https://user-images.githubusercontent.com/42765009/87845317-e213fb80-c8ce-11ea-88f1-b6acd4bd495a.png)
![Screenshot_679](https://user-images.githubusercontent.com/42765009/87845320-e5a78280-c8ce-11ea-93c8-6517664b2d82.png)


Ryzen 3900X, 12 core, hash 1024 MB, no TB.

**Comment by JavaMast** [comment]
> Does the same problem occur on Intel with Cfish 11a (if you are able to test this)? Cfish 271219 seems quite a bit older.
> 
> Are there positions where the problem does not occur?
> 
> On the positions where the problem does occur, does it occur on each run?
> 
> My first thought is a bug in the smp patch just before Cfish 11.

I am not able to test Cfish 11a on Intell CPU now.

if add some pawns to test position the speed of Cfish and Stockfish is almost same

![Screenshot_691](https://user-images.githubusercontent.com/42765009/87872497-d5240480-c9c1-11ea-9e29-eeeba6096c83.png)

![Screenshot_689](https://user-images.githubusercontent.com/42765009/87872508-f553c380-c9c1-11ea-8ada-681eae3d09af.png)


![Screenshot_694](https://user-images.githubusercontent.com/42765009/87872502-d9e8b880-c9c1-11ea-8d89-41110469d958.png)




original position:

![Screenshot_692](https://user-images.githubusercontent.com/42765009/87872599-b40fe380-c9c2-11ea-8fa9-7826aac0aed5.png)

![Screenshot_693](https://user-images.githubusercontent.com/42765009/87872603-ba9e5b00-c9c2-11ea-83fd-e0f644688c41.png)


=======================
> On the positions where the problem does occur, does it occur on each run?
yes, on each run but with some noise in speed (+/- 15%), 
In case of "cold start" - almost always same speed.

**Comment by JavaMast** [comment]
Perhaps the problem is not in Cfish? Maybe Stockfish is unnecessarily increasing the number of nodes?

**Comment by syzygy1** [comment]
Does the same happen when searching with 1 thread?

**Comment by JavaMast** [comment]
No:

![Screenshot_695](https://user-images.githubusercontent.com/42765009/87883134-f0b4fc80-ca0d-11ea-8806-b2711b5b02a5.png)

![Screenshot_696](https://user-images.githubusercontent.com/42765009/87883137-f579b080-ca0d-11ea-8593-514c5d99d763.png)


Looks like it happens when switching from 3 to 4 cores

3 cores:
![Screenshot_703](https://user-images.githubusercontent.com/42765009/87883191-6a4cea80-ca0e-11ea-85c1-3bc98b7dcd54.png)

4 cores:
![Screenshot_702](https://user-images.githubusercontent.com/42765009/87883194-7173f880-ca0e-11ea-84ba-31759c330b09.png)

**Comment by JavaMast** [comment]
Dual Xeon:

![Cfish 11a vs Stockfish 11 comparison](https://user-images.githubusercontent.com/42765009/87883321-3c1bda80-ca0f-11ea-96c6-e3fa2f4b605b.jpg)

**Comment by syzygy1** [comment]
With 4 threads (on my Intel 6-core CPU) I do indeed get higher nps for SF11 than Cfish11a on the position you gave (not as extreme as you are getting with 12 threads, though). With 1 thread, Cfish11a is quite a bit faster.

The nps of SF11 on 4 cores is (slightly) higher than 4x the nps of SF11 on 1 core (which is somewhat surprising). At the same time, Cfish's nps on 4 cores is clearly a lot less than 4x single core nps. On some random other position, I am seeing Cfish getting about 4x the nps of a single thread.

So I guess I can confirm that something strange is going on here.

It doesn't seem to be the SMP patch that I mentioned earlier (disabling it does not seem to make a difference).

Probably this is a case of multiple threads trying to access the same cache lines (which would explain why the problem gets worse as the number of threads increases). Perhaps it is time to allocate one countermovehistory table per search thread instead of one per NUMA node. (But if this is the problem, then it is not clear to me why the problem does not occur in all positions.)

I think your CPU is just one NUMA node, but it might be more affected by cache lines ping-ponging between cores than Intel CPUs.

**Comment by syzygy1** [comment]
Could you try if the "Per-thread CMH tables" patch improves things?

**Comment by JavaMast** [comment]
Excellent!
This issue is fixed.
Thank you!

![Screenshot_782](https://user-images.githubusercontent.com/42765009/89105545-ac245a80-d42a-11ea-87ee-1dd09960788a.png)

![Screenshot_783](https://user-images.githubusercontent.com/42765009/89105548-b181a500-d42a-11ea-8fc1-ba3e311296f6.png)
