### ISSUE TITLE
cfish is much appreciated on playchess

### ISSUE THREAD

**Issue by Denzwell** [syzygy1/Cfish#149]
Personally this is my favorite and I use it from the star.

**What is the possibility of using two polyglot books like in brainfish ???**
it would take a long time ??

Also it would be good to preserve the last modification date of the files

Best regards

**Comment by ArminHHJ** [comment]
Cfish stronger with one brain book, then oki and sf with booth.
Would the second book strengthen this even further?

Mac (10.15.6), MacPro 13, i5, 2.7Ghz

Turnier 0.1sec/move
Cute Chess GUI: 
TB 6 men; 64 MB Hash; standard settings; 1 thread; no ponder; hert250lowdraws.pgn;
Books when possible: both from brainfish (T610 and cerebellum_light)

SF-Naming: 
engine+NNUE - author - git version - nn-version - book(s)

SF: stockfisch-team
MZ: Zerbinati

Brain: use two books

Rank	Name	Elo	+/-	Games	Wins	Losses	Draws	Points	Score	Draw	White	Black
1	CFish+NN-0509-UE308d-T610	41	7	4000	1105	637	2258	2234.0	55.9%	56.5%	58.8%	52.9%
2	Oki-Maguro-12-0309-UE8221-Brain	26	7	4000	1046	752	2202	2147.0	53.7%	55.0%	57.8%	49.6%
3	SF+NN-MZ-1808-UE8221-Brain	22	7	4000	1062	814	2124	2124.0	53.1%	53.1%	55.5%	50.7%
4	SF+NN-SF-0509-UE308d	-38	8	4000	795	1231	1974	1782.0	44.5%	49.4%	48.9%	40.2%
5	CorChess+NN-0509-UE308d	-50	8	4000	714	1288	1998	1713.0	42.8%	50.0%	47.8%	37.9%
10.000 of 10.000 games finished.

Now I will check the new 308d.. nn with SF-MZ and cfish.

**Comment by syzygy1** [comment]
What is the second book doing? Can't they be merged into one big book?

**Comment by Denzwell** [comment]
the first book would contain only victories and the second draws. it's not the same if we merge them

**Comment by syzygy1** [comment]
One book for playing as white and one book for playing as black?

**Comment by Denzwell** [comment]
Indeed the first book would contain the victories of the whites and the second those of the blacks. it would be much appreciated and would bring more to the engine

**Comment by syzygy1** [comment]
OK, I'll have a look at it. Might take a few days before I have time.

**Comment by ArminHHJ** [comment]
Good question, the first book is based on Lc0 games (advantage opening and middle game), when the knowledge ends, the second book grabs with more knowledge (middle and end game AB engines). With only T610 the engine starts calculating much earlier.

I made an experimental book (Axx). Based on NNUE games with the Brain books.

Brainfish uses his books (order: 1st book: Cerebellum_Light_Poly_NetT610.bin (Lc0-based), 2nd book: Cerebellum_Light_Poly.bin). BF was the most powerful engine until Stockfish used NNUE. SF+NN (without books) was immediately equal or stronger. Since then there is no new version of BF. 

I use these books in the compiles of Zerbinati and Oki-Maguro/Honey (can use multiple books, like a Brainfish replacement). So these two engines were the strongest (50-80) Elo stronger than SF+NN from Dev. Since a few days cfish replaced these two, with only one book (T610) :)

I'm not sure if the second book from Brainfish has an advantage. 
Denzwell's idea also sounds interesting. The way of using two books would have to be tested.

Test that is still running:

Rank	Name	Elo	+/-	Games	Wins	Losses	Draws	Points	Score	Draw	White	Black
1	CFish+NN-0509-UE308d-T610	15	16	632	124	97	411	329.5	52.1%	65.0%	56.2%	48.1%
2	SF+NN-MZ-1808-UE308d-T610	7	17	634	127	114	393	323.5	51.0%	62.0%	54.4%	47.6%
3	CFish+NN-0509-UE308d-A40	7	17	634	128	116	390	323.0	50.9%	61.5%	55.4%	46.5%
4	SF+NN-MZ-1808-UE308d-Brain	-2	17	634	120	123	391	315.5	49.8%	61.7%	51.9%	47.6%
5	SF+NN-MZ-1808-UE308d-A40	-27	17	634	105	154	375	292.5	46.1%	59.1%	47.3%	45.0%

Armin

**Comment by Denzwell** [comment]
> 
> 
> OK, I'll have a look at it. Might take a few days before I have time.

the code already exists in brainfish to implement it

**Comment by syzygy1** [comment]
I'll have to reimplement it, but it is pretty trivial.

**Comment by syzygy1** [comment]
What Brainfish does is play a move from the first book if a move is available, otherwise a move from the second book if one is available. So the first book has priority over the second book.

**Comment by Denzwell** [comment]
> 
> 
> What Brainfish does is play a move from the first book if a move is available, otherwise a move from the second book if one is available. So the first book has priority over the second book.

Exactly first book has priority over the second book. it is an advantage for the engine cfish

**Comment by syzygy1** [comment]
I don't know what you mean by preserving the last modification date of the files. Which files?

It seems in Brainfish the BestBookMove and BookDepth options only apply to the first book. For the second book these values are always set to true and 255. Would it not make more sense to use the UCI values for both books?

**Comment by ArminHHJ** [comment]
I think that for Brainfish his A+B engine book made up his game strength (moves to depths of 30 and higher), so that setting for BF is ok. The recommendation is to use the Lc0 based for the first book and the A+B based for the second.

For your own books or books that are still being built, it would certainly be more flexible if the two options could be set for each book.

book1-file: xxx1
book1-deep: 255
book1-best: on/off

book2-file: xxx2
book2-deep: 255
book2-best: on/off

Zerbinati has 3 books but only one (general) possibility to configure them with deep and best (similar to Brainfish??)

Oki-Maguro/Honey has the possibility to set each options each 3 books. I think more than two books is a bit too much flexibility...  :)

Armin

**Comment by syzygy1** [comment]
In case you haven't yet noticed, I have added a BookFile2 option.
The depth and best move settings now apply to both books in the same way (as far as I can tell, Brainfish only applies them to the first book, using the default values for the other).

Instead of a BookFile2 option, I could also just allow the user to set multiple files in BookFile, just like you can set multiple paths in SyzygyPath. This way, the user can use as many books as he want.

**Comment by Denzwell** [comment]
> 
> 
> I don't know what you mean by preserving the last modification date of the files. Which files?
> 
this remark does not concern the implantation of the second book. But the Zip file (Cfish-master.zip) that we download to compile. All files have the same date. We just want to know the last modified files in the new version.

**Comment by Denzwell** [comment]
> In case you haven't yet noticed, I have added a BookFile2 option.
> The depth and best move settings now apply to both books in the same way (as far as I can tell, Brainfish only applies them to the first book, using the default values for the other).

the implementation as in brainfish is more than sufficient. no need to complicate things

**Comment by Denzwell** [comment]
![Cfish_playchess](https://user-images.githubusercontent.com/34477422/92741141-9afe3000-f37e-11ea-9353-7539a6167371.jpg)

**Comment by syzygy1** [comment]
> > I don't know what you mean by preserving the last modification date of the files. Which files?
> 
> this remark does not concern the implantation of the second book. But the Zip file (Cfish-master.zip) that we download to compile. All files have the same date. We just want to know the last modified files in the new version.

I see. I'm afraid that is something that github.com does and is not under my control.

If you install git and "clone" the Cfish repository on your local drive, you can see more easily what has changed.

**Comment by Denzwell** [comment]
> I see. I'm afraid that is something that github.com does and is not under my control.
> 
yes it's github.com fault. i just checked with the other projects. All files have the date of download

**Comment by Denzwell** [comment]
when do you think the implementation of the two books to be up and running. I want to break the news to the community please

**Comment by syzygy1** [comment]
It should be working already. Please try it out, I did not really test it.

**Comment by Denzwell** [comment]
> 
> 
> It should be working already. Please try it out, I did not really test it.

Does not work. All files are the same date in in the Zip file ..

![C_Last_file](https://user-images.githubusercontent.com/34477422/92839487-4f7c6e00-f3e0-11ea-94dd-a9b3f0b02bad.jpg)

**Comment by ArminHHJ** [comment]
Is running on Mac :)
You implemented 2nd book like Brainfish it do?
Thanks for the new feature!

**Comment by syzygy1** [comment]
Yes, see what I wrote earlier. Let me know if BookFile2 does not work or if BookFile is now broken. I did not really test it.

**Comment by JavaMast** [comment]
@ArminHHJ 
Can you please share binary for Mac?

**Comment by JavaMast** [comment]
@syzygy1 
in my tests it works perfect.
Thank you!

**Comment by ArminHHJ** [comment]
@JavaMast 

pls check if it run. copy the net in same folder and check it in configuration.

[CFish-110920-bmi2-clang-noembed-AJ.zip](https://github.com/syzygy1/Cfish/files/5209273/CFish-110920-bmi2-clang-noembed-AJ.zip)

**Comment by syzygy1** [comment]
What are your views on removing BookFile2 and allowing multiple books to be set with the BookFile parameter? Like:
book1.bin;book2.bin;book3.bin
Cfish would then look at these books in the stated order.

**Comment by JavaMast** [comment]
@ArminHHJ 
works fine.
Thank you!

============
A lot of people ask me to compile version for Mac but i have not mac device(

**Comment by AlexB123** [comment]
> 
> 
> What are your views on removing BookFile2 and allowing multiple books to be set with the BookFile parameter? Like:
> book1.bin;book2.bin;book3.bin
> Cfish would then look at these books in the stated order.

I think it is better to keep it as it is (IMHO).

**Comment by maxchess** [comment]
The Mac binary works fine also the multiple book idea is a good one !

**Comment by syzygy1** [comment]
> > What are your views on removing BookFile2 and allowing multiple books to be set with the BookFile parameter? Like:
> > book1.bin;book2.bin;book3.bin
> > Cfish would then look at these books in the stated order.
> 
> I think it is better to keep it as it is (IMHO).

It would reduce the total number of options (making it easier to add other options) and make things even more flexible for those that need many-book functionality.

(I understand that some GUIs have problems with engines having many UCI options.)

**Comment by Denzwell** [comment]
the implementation of the second book is working fine. thank you for its quick realization. Please don't change anything, no extra option for books

**Comment by AlexB123** [comment]
> 
> 
> > > What are your views on removing BookFile2 and allowing multiple books to be set with the BookFile parameter? Like:
> > > book1.bin;book2.bin;book3.bin
> > > Cfish would then look at these books in the stated order.
> > 
> > 
> > I think it is better to keep it as it is (IMHO).
> 
> It would reduce the total number of options (making it easier to add other options) and make things even more flexible for those that need many-book functionality.
> 
> (I understand that some GUIs have problems with engines having many UCI options.)

Maybe it's worth a try, although i'm still on my opinion. It's up to you. :-)

**Comment by syzygy1** [comment]
I guess this can be closed. Please open a new issue if there is a problem with BookFile2 (but I guess it works).
