### ISSUE TITLE
Cannot get CFish 12 to load in Fritz GUI

### ISSUE THREAD

**Issue by tdh1967** [syzygy1/Cfish#153]
I have been able to load every Stockfish version and clone that use NNUE so far in Fritz GUI.  I don't consider myself an expert but I definitely know how to create the engine, instruct the engine to get the NNUE from the correct path, etc., 

I have tried for an hour every windows version of the new Cfish 12 and it will not run in my Fritz GUI.  It gives an error,  ....."caused an exception, there is a problem with the engine....."

I currently run latest ShashCHess 14, BrainLearn 11, as well as Sept. 8 release of Stockfish.  I even change the nets often to try out the differences in nets, so I know how to do the basics.  If anyone has the same trouble in Fritz GUI, I would appreciate any advice if you end up getting it to work.  Thank you.

**Comment by syzygy1** [comment]
Please try Cfish_12_x86_64_windows.zip with embedded net.

**Comment by syzygy1** [comment]
Unfortunately something went wrong wth the embedded-network versions. They are still looking for a network file. I will remove them for the moment and fix the problem later.

They should still work if you configure the (external) net file correctly, though.

**Comment by syzygy1** [comment]
I've removed the whole release for the moment. It'll be back later today.

**Comment by tdh1967** [comment]
Thank you.

I did try what you suggested last night as I continued to try to make it work but it continued with the same error.

**Comment by syzygy1** [comment]
Do you know what CPU you have? Or which compile of Stockfish works on your system?

As far as I can tell, cfish12_x86-64_windows.exe should have worked on any system with a 64-bit Windows OS (but required the old nn-82215d0fd0df.nnue file to be present in exactly the "right" folder).

**Comment by syzygy1** [comment]
Could you try if any of the cfish_11a compiles works on your system with Fritz?

**Comment by tdh1967** [comment]
Checking and getting that info for you.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tdh1967** [comment]
I tried the version of CFish 11a and although it took slightly longer to load than usual, it runs fine. (It even correctly and very quickly picks Fischer's 39 move as black in game#1 1972 as a losing move, the real losing move.)  I chose the windows only version by the way.
 
My system:
Intel Core i7-4700MQ CPU @ 2.40 GHz, 8 GB RAM, latest windows version.

**Comment by lex312** [comment]
I have the same problem.
Cfish can‘t be loaded when I use Fritz 13 gui, Fritz 16 gui or ChessBase 15 gui.
Cfish runs without problems when I use ChessOK Aquarium 2020 gui.

Maybe ChessBase/Fritz have a problem/bug and not Cfish.
Or Cfish is missing something to run fine in the ChessBase products.

I‘m using an i7 3930k @ 4.2 GHz (which Cfish should I use?)
64 GB RAM
Windows 8.1

**Comment by tdh1967** [comment]
I didn't mention that I tried bmi2, avx2, and regular windows version last night. At first, I was trying to use the August 13th net (the first one released on Aug. 13) but after many tries and failing with each version of the embedded and stand alone .exe versions of the same bmi2, avx2, and windows and then finally putting the exact path, even creating an eval folder and entering that path (trying this as a longshot), I gave up and repeated all of this with the default net.  I continued to get the error.  However, I did not try the old default you mentioned a while ago. I had only been trying the default that came embedded and the Aug 13 first net (I forget the exact file name.  

I will try the one you mentioned.

**Comment by JavaMast** [comment]
@tdh1967 
Try my compilations:
https://pixeldrain.com/u/sq4njmkY

should work in Fritz GUI

**Comment by syzygy1** [comment]
Thanks!
If Fritz can run Cfish 11, it should also be able to run Cfish 12 with embedded net.
However, the previous "embedded" versions were buggy.
I think non-embedded versions should have worked, but it may have looked for the network file in a different folder (which can be solved by specifying the full path starting from C: or D:) or there may have been a typo. (From what you write I understand you were very careful, so it is still a bit of a mystery to me why nothing worked.)

I am attaching a build with embedded network that should work.
[cfish_12_x86-64_windows.zip](https://github.com/syzygy1/Cfish/files/5219185/cfish_12_x86-64_windows.zip)
It is not the fastest, but let's try this one first.

If it does not work in Fritz, could you trying running it from a DOS prompt?
Just type cfish_12_x86-64_windows or whatever you have named it. It it starts, type bench.

With the i7-4700MQ the avx2 version should work and probably also the bmi2 version (which should be the fastest). So the problem was almost certainly not caused by illegal instructions (e.g. from running avx2 on a CPU that does not support avx2).

For the i7-3930K, use the sse41-popcnt one (aka "modern").

**Comment by tdh1967** [comment]
Thank you. I will try it now.

**Comment by tdh1967** [comment]
Also, I will try that too JavaMast. Thank you.

**Comment by tdh1967** [comment]
To syzygy1: It works! Thank you.

**Comment by syzygy1** [comment]
Great! Thank for testing and sorry for what must have been a frustrating night ;-)
I'll put up the other binaries later today.

**Comment by tdh1967** [comment]
To Sysgy1: Glad to help. I'll look for those later.

**Comment by tdh1967** [comment]
To Javamast:  It works great.  I used BMI2 and the first net from Aug. 13, which has shown just a little stronger for me.  Thank you.
