### ISSUE TITLE
Cfish starts the analysis every time after 1.5 seconds

### ISSUE THREAD

**Issue by lex312** [syzygy1/Cfish#154]
For example when I run some test suites using the Fritz gui, Cfish starts the analysis with every new position, after 1.5 seconds.
Why this is happening?
Other engines, for example LC0 starts the analysis instantly.

-I can confirm that Cfish 12 from syzygy1 works in Fritz gui and ChessBase gui, but the compile from JavaMast doesn‘t work.
https://github.com/syzygy1/Cfish/issues/153
I hope to see some updates to run the newest Cfish :-)

**Comment by syzygy1** [comment]
If you set hash to 16 MB, does the delay disappear?

**Comment by lex312** [comment]
@syzygy1 yes.
But what does it mean?
I have 64 GB RAM.
When I use LC0 and 32 GB RAM, the analysis starts every time instantly.
When I use Cfish and 32 GB RAM, the analysis starts every time after 1.5 seconds.
When I use Stockfish (12 or dev.) and 32 GB RAM, the analysis starts every time after 2.5 seconds.

**Comment by lex312** [comment]
And how much RAM should I use for 1 sec. per position and 7500 kn/s?

**Comment by syzygy1** [comment]
So the delays are caused by Cfish and Stockfish clearing the hashtable between positions in response to Fritz sending them either a "ucinewgame" or a "setoption name Clear Hash" command. Lc0 apparently doesn't do that, for whatever reason.

If you 1-second searches, it makes absolutely no sense to use a 32GB hash table. With 7500kn you store at most 7.5 million posiitons. A hashtable of 64MB stores 12 million positions.
