### ISSUE TITLE
Cfish on Windows

### ISSUE THREAD

**Issue by cosmic4444** [syzygy1/Cfish#17]
From October compilations of Cfish doesn't work on Windows ("Couldn't load engine"), what can be the reason? Thank you

**Comment by syzygy1** [comment]
Is this (still?) a problem for anyone?

**Comment by CoffeeOne** [comment]
No problem here, worked always for me.

**Comment by ChessMan3** [comment]
Hello!
The description says "Not fully tested on Windows." Are you planning to improve the engine performance under this system (in terms of speed increase) or is it the maximum? I'm interested because in Linux, with LTO enabled, Cfish has become faster than ASMfish, even on one core.

========
AMD FX-8150 @4.0 GHz, OS Linux Mint 18.2 cinnamon (x64), Cfish compiled with Gcc-5 (5.4.0-6ubuntu1~16.04.5) & my makefile (LTO enabled)

**Cfish "bench"** (Updated to "Handle BxN trade as good capture when history score is good".)
Total time (ms) : 2859
Nodes searched : 5482249
Nodes/second : 1917540

Total time (ms) : 2900
Nodes searched : 5482249
Nodes/second : 1890430

Total time (ms) : 2883
Nodes searched : 5482249
Nodes/second : 1901577

**ASMfish "bench":**
Total time (ms) : 2940
Nodes searched : 5482249
Nodes/second : 1864710

Total time (ms) : 2902
Nodes searched : 5482249
Nodes/second : 1889127

Total time (ms) : 2930
Nodes searched : 5482249
Nodes/second : 1871074

=======
Also I held a match between them and Cfish was stronger
1 core, 1 sec per move, 256 MB hash, book test1.pgn (100 positions), GUI Arena 1.1 for Linux (started in 6 windows).

Summary results: 
**CFish  614.5/1200**, Winning percentage 51.25%, Elo difference: +8
**ASMfish  585.5/1200**, Winning percentage 48.79%, Elo difference: -8

Download games in PGN: http://www71.zippyshare.com/v/RTd3Gj2g/file.html

**Comment by syzygy1** [comment]
I need to update the README some time :-)
