### ISSUE TITLE
Long delay for hash initialization?

### ISSUE THREAD

**Issue by LouisZulli** [syzygy1/Cfish#39]
Dual 10-core Linux system with 64 GB RAM. There is a 35-second delay between the messages about binding threads and the info depth 1 message. The length of the delay increases with the size of the hash table, so I assume the delay is related to hash initialization.

I don't recall this happening in the past. Is this an artifact of the switch to arbitrary hash sizes? I note a similar (but smaller) delay with Stockfish 9 as well.

Thanks for offering Cfish!

```
Cfish 090218 64 POPCNT NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Threads value 20
setoption name Hash value 32768
go infinite
info string Binding thread 0 to node 0.
info string Binding thread 1 to node 0.
info string Binding thread 2 to node 0.
info string Binding thread 3 to node 0.
info string Binding thread 4 to node 0.
info string Binding thread 5 to node 0.
info string Binding thread 6 to node 0.
info string Binding thread 7 to node 0.
info string Binding thread 8 to node 0.
info string Binding thread 9 to node 0.
info string Binding thread 10 to node 1.
info string Binding thread 11 to node 1.
info string Binding thread 12 to node 1.
info string Binding thread 13 to node 1.
info string Binding thread 14 to node 1.
info string Binding thread 15 to node 1.
info string Binding thread 16 to node 1.
info string Binding thread 17 to node 1.
info string Binding thread 18 to node 1.
info string Binding thread 19 to node 1.

**About 35 seconds pass between the above message and the one below.**

info depth 1 seldepth 1 multipv 1 score cp 102 nodes 1192 nps 397333 tbhits 0 time 3 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 38 nodes 4544 nps 1136000 tbhits 0 time 4 pv d2d4 d7d5

```

**Comment by syzygy1** [comment]
The delay has probably been there since this patch:
https://github.com/syzygy1/Cfish/commit/1724cab6d6db54413227a1bc68cb420583760c60#diff-cfb42647f460cb87f3decb6b388a5cb1

It may be possible to revert to the old behaviour on start-up, but I just verified that older versions are slow during the first seconds if the TT is large. That is not ideal either.

If the user or GUI issues "isready" before the search is started, the TT is cleared (and its memory pages are paged in, which is what is taking time here) before the search is started.

I will see if something can be improved here.

**Comment by syzygy1** [comment]
When I set LargePages to false before issuing "isready", initialisation time is even longer:

$ time ./cfish
Cfish 110218 64 POPCNT NUMA by Syzygy based on Stockfish
setoption name Hash value 16384
setoption name LargePages value false
isready
readyok
quit

user	0m0.910s
sys	0m3.668s

$ time ./cfish
Cfish 110218 64 POPCNT NUMA by Syzygy based on Stockfish
setoption name Hash value 16384
isready
readyok
quit

user	0m0.611s
sys	0m1.222s

(I have removed the "real" timings to avoid confusion.)

**Comment by syzygy1** [comment]
So if possible, make sure that transparent hugepage support is not disabled.
$ cat /sys/kernel/mm/transparent_hugepage/enabled 
always [madvise] never

(Or [always])

**Comment by syzygy1** [comment]
Stockfish is as slow as Cfish without LP on my system:

$ time sf_9
Stockfish 9 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name Hash value 16384
isready
readyok
quit

user	0m0.967s
sys	0m3.670s

**Comment by syzygy1** [comment]
If Cfish is slower on your system, it may have to do with NUMA. Cfish tells the kernel to interleave the TT on all nodes, which is supposed to give better performance. You could try setting the UCI NUMA option to "off" before issuing isready to see if it makes a difference for initialisation time. (I have no NUMA system to test this.)

This may be just a problem of my mainboard, but without setting LargePages to false my computer makes quite a bit of noise (I think it's coil whine) during the 1.2 seconds that it takes to page in the TT memory. I think this has to do with cores quickly starting up and down, although I'm not sure why large/huge pages would cause that. (It is also something that happens during TB generation, in particular when generating TBs like KPPvKPP when threads are continuously being started and stopped to deal with many small pawn slices.)

Btw:
$ time ./cfish
Cfish 110218 64 POPCNT NUMA by Syzygy based on Stockfish
setoption name Hash value 32768
isready
readyok
quit

user	0m1.357s
sys	0m13.176s

$ time ./cfish
Cfish 110218 64 POPCNT NUMA by Syzygy based on Stockfish
setoption name Hash value 32768
setoption name LargePages value false
isready
readyok
quit

user	0m1.768s
sys	0m7.560s


So with 32GB instead of 16GB the use of LP actually slows things down!
I also noticed that without LP the "quit" command takes a bit longer, so the difference in initialisation time is even larger.

**Comment by LouisZulli** [comment]
Thanks for the fast replies. Currently, I don't have access to the 
computer. I shall investigate further when I can, but for now I'll 
point out that I never sent the isready command. I simply sent 
setoption commands to set the number of threads and the size of the 
hash table, and then I sent go infinite. With a 32 GB table, there was 
a 35 second delay between the binding threads messages and the first 
depth 1 info. Not sure if my not sending isready matters to the 
discussion at hand.

**Comment by LouisZulli** [comment]
On Sun, Feb 11, 2018 at 10:37 AM, syzygy1 <notifications@github.com> 
wrote:
> If Cfish is slower on your system, it may have to do with NUMA.

About large pages, my system has transparent hugepages supported 
[always]. Disabling LargePages in Cfish gave a very small speed-up in 
initializing a 32 GB hash, as you noted as well.

Yes, NUMA is really exacerbating the problem:

time ./cfish
Cfish 090218 64 BMI2 NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Hash value 32768
isready
info string Binding thread 0 to node 0.
readyok
quit

user	0m1.656s
sys	0m36.984s

-------------------------------------------------

time ./cfish
Cfish 090218 64 BMI2 NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Hash value 32768
setoption name Threads value 20
isready
info string Binding thread 0 to node 0.
info string Binding thread 1 to node 0.
info string Binding thread 2 to node 0.
info string Binding thread 3 to node 0.
info string Binding thread 4 to node 0.
info string Binding thread 5 to node 0.
info string Binding thread 6 to node 0.
info string Binding thread 7 to node 0.
info string Binding thread 8 to node 0.
info string Binding thread 9 to node 0.
info string Binding thread 10 to node 1.
info string Binding thread 11 to node 1.
info string Binding thread 12 to node 1.
info string Binding thread 13 to node 1.
info string Binding thread 14 to node 1.
info string Binding thread 15 to node 1.
info string Binding thread 16 to node 1.
info string Binding thread 17 to node 1.
info string Binding thread 18 to node 1.
info string Binding thread 19 to node 1.
readyok
quit

user	0m1.692s
sys	0m36.256s

-------------------------------------------------
 time ./cfish
Cfish 090218 64 BMI2 NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Hash value 32768
setoption name NUMA value off
info string NUMA disabled.
isready
readyok
quit

user	0m1.632s
sys	0m11.740s

**Comment by syzygy1** [comment]
Is it much faster if you disable NUMA?

$ time ./cfish
setoption name NUMA value off
isready
quit

As far as I can tell, the SF delay is equal to the Cfish delay if large pages are not used (or, I guess, if they are used "always", in which case SF cannot avoid using them too, on Linux). Clearly it is not a good option to disable LP just to get rid of the delay.

One option is to avoid initialising all of the TT table at startup, i.e. the old behaviour. But this would only hide the delay: Cfish would start searching with pretty low nps until finally most of the TT has been paged in. It is probably faster overall to page in all at once.

To verify this, you can try out asmFish. When I give it a 32GB hash and type "go infinite", it will start searching immediately, but nps is about 500knps instead of well over 2Mnps. It's even worse for cfish8 (which has the old behaviour): it takes about 5 seconds to reach a mere 100knps. The difference is explained by asmFish not using LP (indeed, cfish8 with LP disabled quickly reaches about 480knps).

So at present I think this delay has to be accepted...

Whether you type isready or not is indeed not important. But it is important that GUIs issue an isready command to tell the engine to finish its initialisation before game play starts.

**Comment by LouisZulli** [comment]
On Sun, Feb 11, 2018 at 4:54 PM, syzygy1 <notifications@github.com> 
wrote:
> Is it much faster if you disable NUMA?

Yes, it takes only one third the time. This was included in my last 
reply:

 time ./cfish
Cfish 090218 64 BMI2 NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Hash value 32768
setoption name NUMA value off
info string NUMA disabled.
isready
readyok
quit

user	0m1.632s
sys	0m11.740s

Thanks for the assistance. Not a major problem, but wanted to be sure 
it was not unique to my machine!

**Comment by syzygy1** [comment]
Ah, I had missed the end of the reply.

OK, so there is another option, which is to disable interleaving of the TT table.
https://github.com/syzygy1/Cfish/blob/e3b0c8cfa730eae02e9c998f25140d75daf605ea/src/tt.c#L129-L130
If you comment out these two lines and leave NUMA on, does the same procedure take 36 or 12 seconds? Probably just 12.

So then the question becomes whether those extra 24 seconds are worth the gain.

**Comment by LouisZulli** [comment]
On Sun, Feb 11, 2018 at 5:52 PM, syzygy1 <notifications@github.com> 
wrote:
> If you comment out these two lines and leave NUMA on, does the same 
> procedure take 36 or 12 seconds? Probably just 12.
> 
With no interleaving, 12 seconds.

Btw, gcc-6 doesn't like one of the new optimization flags:

gcc-6: error: unrecognized command line option 
‘-flimit-function-alignment’; did you mean ‘-fipa-cp-alignment’?

**Comment by syzygy1** [comment]
So numa_interleave_memory() slows down paging in the TT by 24 seconds.
That can probably be improved on a lot by not interleaving the memory across nodes on a page-by-page basis but e.g. letting each thread page in its own slice of the TT. Since the TT is accessed randomly, it does not matter how it distributed over the nodes. As a bonus, it will also work on Windows.

**Comment by syzygy1** [comment]
My latest commit might reduce the delay considerably.
time will now report cumulative user and sys time of all threads, which is less useful.
A good measurement might be this:

$ time ./cfish bench 32768 6 1 >/dev/null
real	0m5.032s

Where 6 is the number of threads.
It seems there is no big speed up beyond 2 threads on my machine (at least during initialisation), but this should also get rid of the NUMA 3x penalty (without costing performance during the actual search).

**Comment by jjoshua2** [comment]
Is it possible to also mitigate this like asmfish does where ponder is used during the opening book so hash table is properly initialized and seeded by the time we're out of book?

**Comment by syzygy1** [comment]
I may add it, but the hash table is already initialised before the clock starts ticking (as long as the GUI sends isready).

**Comment by syzygy1** [comment]
How long is the delay now?

**Comment by LouisZulli** [comment]
Much shorter. Barely noticeable compared to what it was. Thanks!

**Comment by syzygy1** [comment]
And thank you bringing the problem to my attention and helping to understand it better.
