### ISSUE TITLE
Dynamic part of "contempt"

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#47]
Hello! Can you please make button to disable the dynamic part of this?
The dynamic part has no good effect in analysis, IMO.

I tryied this:
if (option_value(OPT_CONTEMPT_DYNAMIC))
        {
        // Adjust contempt based on current situation
        int ct = base_ct + (  bestValue >  500 ?  50
                            : bestValue < -500 ? -50
                            : bestValue / 10);
        store_rlx(Contempt, pos_stm() == WHITE ?  make_score(ct, ct / 2)
                                               : -make_score(ct, ct / 2));
        }

it works fine for me in analysis.

**Comment by jjoshua2** [comment]
If you set contempt to 0 the dynamic part won't hurt analysis since its the same for both sides and in testing it increased playing strength. With this patch your analysis will be weaker. Just like if you removed something else beneficial like king safety.
It's mostly badly named to be contempt instead of something like attack coefficient

**Comment by ChessMan3** [comment]
Contempt 0 is not helps - this part is still working. I checked this on several positions (maybe need more) and without dynamic part the strongest moves were found faster.
4rb2/1p1q1ppk/p1n1p2p/2p1Pn2/3PNR2/2P2K2/P2QBP2/6R1 w - - 0 1  1.R*f5
2r1r1k1/pp1b1p1p/1n2pqp1/4B3/3P4/3B2Q1/PP3PPP/R3R1K1 b - - 0 18   18...Qd8? 19.Re4!

**Comment by jjoshua2** [comment]
That's such a small sample size. I'm sure there are a lot more positions
where it helps.
To go back to the king safety example, in positions where there is no
checkmate that code is likely to make those slower to find the best move
too but it doest mean you take out that code for analysis because you don't
know what type of position it is ahead of time.
