### ISSUE TITLE
Changing bench

### ISSUE THREAD

**Issue by Krgp** [syzygy1/Cfish#66]
I just compiled (gcc 7.3.0 rev2 by msys2 on Win 10 Pro 64 bit  --> make profile-build ARCH=x86-64-bmi2 ) a Cfish build from Process TT/Hash/Numa settings when receiving ucinewgame 5162137cf263f2a18c4513cd43d6a8f1252aeb01.

Every time i 'bench' i get a different one

for e.g.

![cfish310518 bench 1](https://user-images.githubusercontent.com/18749901/40870406-384da632-664c-11e8-998f-1c2e96650d89.png)
![cfish310518 bench 2](https://user-images.githubusercontent.com/18749901/40870407-389f329a-664c-11e8-8ef6-dbd3e1081679.png)
![cfish310518 bench 3](https://user-images.githubusercontent.com/18749901/40870408-38deb406-664c-11e8-8fc7-6934a2ad12d0.png)

Is something wrong or is it just me?

P.S. none of the source files were modified in any way ... strictly default sources including make file were used. I also repeated this many times after each reboot (cold reboot) ... seems reproducible ...

**Comment by ChessMan3** [comment]
I have the same issue - bench is changing. 
Stockfish have not this issue.

**Comment by ChessMan3** [comment]
First commit wich i can build with this issue is 

**Fix compilation under MingW.
syzygy1 committed 13 days ago**


"Merge branch 'master' of https://github.com/syzygy1/Cfish"
 and 
"Use open addressing for the TB entry hash table."
 have not this problem.

But i can not build 2 commits between.
It's:

**Fix compilation error.  …
syzygy1 committed 13 days ago**

**Coding style improvements.
syzygy1 committed 13 days ago**

**Comment by syzygy1** [comment]
Thanks for reporting. This was indeed a bug in "Coding style improvements" (incomplete renaming of a variable, but somehow it still compiled).
